#!/bin/sh
# Modified under MIT © Sindre Sorhus - sindresorhus.com
# git hook to run commands after `git pull` if specified files were changed

changed_files="$(git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2" && [ -n "$3" ] && echo -e "$3"
}

check_run package-lock.json "npm i --silent" " ↳📦 \033[01;33mPackage dependencies were updated. \n\033[0m"
